### ISSUE TITLE
Update @pulumi/pulumi nodejs dep to 3.0

### ISSUE THREAD

**Issue by timmyers** [pulumi/pulumi-spotinst#106]
Currently incompatible with pulumi 3.0

## Expected behavior
Version 3.0 should work with @pulumi/pulumi 3.0

## Current behavior
```
Found incompatible versions of @pulumi/pulumi. Differing major versions are not supported.

  Version 3.0.0 referenced at node_modules/@pulumi/pulumi/package.json

  Version 2.25.2+dirty referenced at node_modules/@pulumi/spotinst/node_modules/@pulumi/pulumi/package.json
```

## Steps to reproduce
Attempt to use with `@pulumi/pulumi 3.0`

**Comment by stack72** [comment]
Hi @timmyers 

I'll get on this right away - not sure how this was missed :/

It will be out in a couple of hours

Paul

**Comment by timmyers** [comment]
No problem, there's no rush, I know you all have a holiday today!

**Comment by stack72** [comment]
Ah it's my mistake so I'll be dealing with it now :)

**Comment by stack72** [comment]
Hey @timmyers 

I just pushed v3.1.0 (build is running right now) and it fixes this issue! Sorry again for this

P.
