### ISSUE TITLE
[ERROR] json: cannot unmarshal number 33.33333333333333 into Go struct field Progress.progress.value of type int

### ISSUE THREAD

**Issue by jasminen** [pulumi/pulumi-spotinst#22]
Hey,
Using the last provider version of pulumi-spotinst (2.3.0) and getting the following while trying to update Elastigroup:
`[ERROR] Timed out when waiting for minimum roll percentage: did not reach target deployment amount: call to roll status of group "sig-xxxxxx" failed: json: cannot unmarshal number 33.33333333333333 into Go struct field Progress.progress.value of type int`

It seems that it cannot accept a non-integer number although that can be the value of a roll group percentage status received from spotinst . In this case the group has 3  instances and only one finished rolling.

**Comment by jaxxstorm** [comment]
Hey @jasminen - could you share the code you used to reproduce this?

**Comment by jasminen** [comment]
@jaxxstorm Just used spotinst.aws.Elastigroup . 
To reproduce: Keep an Elastigroup of 3 instances (min = max = desired = 3), make a change to let's say userdata and apply changes.
The issue here is that spotinst roll status response can be float (percentage) while the provider expects an Int - hence the exception.

**Comment by jasminen** [comment]
@jaxxstorm Any update on this? We can't move forward with spotinst provider due to this issue.

**Comment by jasminen** [comment]
Opened a case to Spotinst - they have resolved it in Terraform provider version 1.32.0:
https://github.com/spotinst/terraform-provider-spotinst/blob/main/CHANGELOG.md#1320-december-21-2020
