### ISSUE TITLE
Lost docs during upgrade

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi-spotinst#366]
### What happened?

As part of reviewing https://github.com/pulumi/pulumi-spotinst/pull/364, I noticed we seemed to drop some docs from the schema (and downstream codegen). I don't see any upstream cause. 

The update is pretty mild, and no docs were removed:

https://github.com/spotinst/terraform-provider-spotinst/commit/3454055f4964c7ecaf6cb1d41b35f7d8b42e9db7#diff-8ee5ce3e992394a0a5d7faca987c34b22332ab1daebb3b5de8c6e66131121f3e

### Expected Behavior

We don't drop docs unless upstream does.

### Steps to reproduce

See https://github.com/pulumi/pulumi-spotinst/pull/364

### Output of `pulumi about`

NA

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by guineveresaenger** [comment]
This was fixed, likely via the refactor of handling Examples sections, via upgrade to https://github.com/pulumi/pulumi-terraform-bridge/releases/tag/v3.77.0 in https://github.com/pulumi/pulumi-kafka/pull/362. 🎉 

See our docs on the registry: https://www.pulumi.com/registry/packages/kafka/api-docs/topic/
